### ISSUE TITLE
[4.9.0] Bug: Incorrect pooling/stacked amount shown in Desktop Wallet

### ISSUE THREAD

**Issue by jdvanbru** [hirosystems/desktop-wallet#1150]
Bug found testing Hiro Wallet build undefined, 4.8.0.

**Comment by markmhx** [comment]
Thanks for the report. Mind sharing a screenshot of what you see? Is the pooling amount specifically wrong, or is the amount of STX that are _locked_ for Stacking wrong?

Possibly related: https://github.com/hirosystems/stacks-wallet/issues/1149

**Comment by jdvanbru** [comment]
Perhaps, the amount stacked and the amount pooled are/can be different?

The amount stacked appears to be correct, but shows 0 pooling.

**Comment by 314159265359879** [comment]
This issue is not resolved yet and popping up again now. Edu's comments about this in another issue https://github.com/hirosystems/desktop-wallet/issues/1155#issuecomment-1490535902

A user who delegated recently using the latest 4.9.0 Desktop wallet saw this after delegating STX at the end of cycle 56 (2 days to go for the start of 57) with the Desktop wallet. 
https://explorer.hiro.so/txid/0xb89490ec1680810fc9e8f14172f7e091f8139fb541daaeae5f2f1d8cd0ba3afe?chain=mainnet
![image](https://user-images.githubusercontent.com/33360391/231974355-7c4b9bdd-66e6-4d30-ae2b-e8fc4e48cdf9.png)

After using the lockstacks.com dapp with the extension instead the Desktop wallet shows:
![image](https://user-images.githubusercontent.com/33360391/231974476-dc7195b8-d25f-41d1-ac03-5e87b4a12b4d.png)
and
![image](https://user-images.githubusercontent.com/33360391/231974595-5d4e3ad3-5a98-4ed3-99cc-f5285225c9d7.png)

In the lockstacks.com dapp it shows like this:
![image](https://user-images.githubusercontent.com/33360391/231975212-a2da46ef-3324-4762-9ede-ad2258b6b3ea.png)

**Comment by markmhx** [comment]
This is getting resolved by https://github.com/hirosystems/desktop-wallet/pull/1188
